language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PINS="mirage-kv-mem.dev:https://github.com/mirage/mirage-kv-mem.git"
   - PACKAGE="crunch"
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.05
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=alpine OCAML_VERSION=4.07
